{
  "hash": "280d7c921b547bf01c1d4d52d4400558",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Beyond Correlation: Association vs. Concordance in Non-Linear Data\"\ndescription: \"Concordant and discordant pairs counted by hand, three correlation coefficients rebuilt from scratch, and what happens when the data is shaped like a dinosaur\"\ndate: 2026-08-26\nauthor:\n  - name: \"Methylation & Colitis team\"\n  - name: \"Ravi Kalia\"\n    affiliation: \"Visiting Scientist\"\ncategories: [statistics, correlation, non-linear, methods, reproducibility]\nimage: \"../../media/illustrations/cover-methylation-statistics.webp\"\nbibliography: ../../references.bib\ncsl: ../../apa.csl\nlink-citations: true\nlink-bibliography: true\nformat:\n  html:\n    code-fold: show\n    code-copy: true\n    code-summary: \"Show the R code\"\n    toc: true\n    toc-depth: 3\n    smooth-scroll: true\n    fig-width: 8\n    fig-height: 5\nexecute:\n  echo: true\n  eval: true\n  message: false\n  warning: false\n---\n\n\n\n::: {.lead-panel}\n## The conclusion first\n\n**Association** is any statistical dependence between two variables. **Concordance** is\nthe much narrower claim that when one variable rises, the other rises too — measured by\ncounting how many pairs of observations agree in their ordering. Pearson's $r$ measures\nneither: it measures *linear* association, and it is the least robust of the three\ncoefficients in common use.\n\nThis post rebuilds concordant-pair counting, Kendall's $\\tau$, Spearman's $\\rho$,\ndistance correlation, and mutual information from scratch in base R, validates each\nagainst the reference implementation, and runs them on two real datasets. Three results\nmatter for this project:\n\n1. A **single mistyped measurement** collapses Pearson's $r$ from $+0.66$ to $+0.03$\n   while Kendall's $\\tau$ moves from $+0.483$ to $+0.475$.\n2. In the Datasaurus, concordant and discordant pairs come out nearly equal\n   ($C = 4{,}710$ vs. $D = 5{,}191$), so $\\tau \\approx 0$ despite obvious structure.\n3. Distance correlation and mutual information have **positive bias floors** — they never\n   read zero, even under genuine independence — so an uncalibrated \"dCor $= 0.16$, therefore\n   dependence\" claim is unsound. Permutation calibration is not optional.\n:::\n\n![Every coefficient in this post answers a different question about the same scatter plot. Choosing one is a modelling decision, not a formatting decision.](../../media/illustrations/cover-methylation-statistics.webp){.science-visual fig-alt=\"Illustration of statistical analysis applied to methylation data\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Show setup and package versions\"}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(knitr)\nlibrary(datasauRus)\nlibrary(palmerpenguins)\n\nset.seed(2026)\n\ntheme_set(\n  theme_minimal(base_size = 12) +\n    theme(\n      panel.grid.minor = element_blank(),\n      plot.title       = element_text(face = \"bold\"),\n      plot.subtitle    = element_text(colour = \"grey35\"),\n      legend.position  = \"top\"\n    )\n)\n\n# A consistent palette across every figure in this post.\npal <- c(Adelie = \"#167d78\", Chinstrap = \"#b8634f\", Gentoo = \"#123b5d\")\n```\n:::\n\n\n\n## Q: What's the fundamental difference between Association, Concordance, and Discordance?\n\nThe three words describe progressively stronger claims about a pair of variables\n$(X, Y)$.\n\n**Association** is the weakest and most general: $X$ and $Y$ are associated if they are\nnot statistically independent, i.e. $P(X, Y) \\neq P(X)\\,P(Y)$. Nothing is said about\ndirection, shape, or monotonicity. A perfect ring, a parabola, and a straight line are\nall strongly associated.\n\n**Concordance** and **discordance** are properties of a *pair of observations*, not of\nthe dataset as a whole. Take any two distinct observations $(x_i, y_i)$ and\n$(x_j, y_j)$. The pair is\n\n$$\n\\begin{aligned}\n\\textbf{concordant} \\quad &\\text{if} \\quad (x_i - x_j)(y_i - y_j) > 0, \\\\[2pt]\n\\textbf{discordant} \\quad &\\text{if} \\quad (x_i - x_j)(y_i - y_j) < 0, \\\\[2pt]\n\\textbf{tied} \\quad &\\text{if} \\quad (x_i - x_j)(y_i - y_j) = 0.\n\\end{aligned}\n$$\n\nA concordant pair agrees on the ordering — the observation with the larger $x$ also has\nthe larger $y$. A discordant pair disagrees. Counting these across all\n$\\binom{n}{2}$ pairs and taking the normalised difference gives Kendall's\n$\\tau$ [@kendall1938]. Spearman's $\\rho$ [@spearman1904] takes a related but distinct\nroute: it applies Pearson's formula to the *ranks* rather than the raw values.\n\nThe critical asymmetry: **concordance implies association, but association does not\nimply concordance.** A perfectly symmetric parabola has $C = D$ exactly, so\n$\\tau = 0$, while $X$ determines $Y$ completely.\n\n| | **Pearson's $r$** | **Spearman's $\\rho$** | **Kendall's $\\tau$** | **dCor / MI** |\n|---|---|---|---|---|\n| **Measures** | Linear association | Monotone association | Concordance | Any association |\n| **Mathematical condition** | $\\dfrac{\\operatorname{cov}(X,Y)}{\\sigma_X \\sigma_Y}$ | Pearson's $r$ on $\\operatorname{rank}(X), \\operatorname{rank}(Y)$ | $\\dfrac{C - D}{C + D}$ | $\\dfrac{\\operatorname{dCov}}{\\sqrt{\\operatorname{dVar}_X \\operatorname{dVar}_Y}}$ / $\\sum p \\log \\frac{p_{xy}}{p_x p_y}$ |\n| **Operates on** | Raw values | Ranks | Pairwise orderings | Distances / binned densities |\n| **Rank sensitivity** | None — uses magnitudes | Full — magnitudes discarded | Full — only orderings used | Partial (dCor uses distances) |\n| **Outlier handling** | **Fragile.** One point can dominate | Robust — an outlier moves one rank | **Most robust** — an outlier flips few pairs | dCor fragile; MI depends on binning |\n| **Detects non-monotone structure** | No | No | No | **Yes** |\n| **Zero means** | No *linear* relation | No *monotone* relation | $C = D$ | Independence (in the population) |\n| **Reads zero under independence?** | Approximately | Approximately | Approximately | **No — positive bias floor** |\n| **Cost** | $O(n)$ | $O(n \\log n)$ | $O(n^2)$ naive, $O(n \\log n)$ optimal | $O(n^2)$ |\n\nThe last two rows are where practitioners get hurt, and §3 is devoted to them.\n\n## Q: How do these metrics perform on biological morphometrics?\n\nThe Palmer Archipelago penguin dataset records body measurements for three species across\nthree islands — a genuine morphometric dataset with the awkward properties real biology\ntends to have.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Load and check the morphometric data\"}\npeng <- penguins %>%\n  select(species, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g) %>%\n  na.omit()\n\nnormality <- data.frame(\n  Trait = c(\"Bill length (mm)\", \"Flipper length (mm)\"),\n  n     = nrow(peng),\n  `Shapiro-Wilk W` = c(\n    shapiro.test(peng$bill_length_mm)$statistic,\n    shapiro.test(peng$flipper_length_mm)$statistic\n  ),\n  `p-value` = format.pval(\n    c(shapiro.test(peng$bill_length_mm)$p.value,\n      shapiro.test(peng$flipper_length_mm)$p.value),\n    digits = 3\n  ),\n  check.names = FALSE\n)\n\nkable(normality, digits = c(0, 0, 4, 0), align = \"lrrr\",\n      caption = \"Both traits reject normality decisively. The cause is structural, not contamination.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Both traits reject normality decisively. The cause is structural, not contamination.\n\n|Trait               |   n| Shapiro-Wilk W|  p-value|\n|:-------------------|---:|--------------:|--------:|\n|Bill length (mm)    | 342|         0.9749| 1.12e-05|\n|Flipper length (mm) | 342|         0.9515| 3.54e-09|\n\n\n:::\n:::\n\n\n\nBoth traits fail a normality test, and it is worth being precise about *why*: this is a\n**mixture of three species**, each with its own mean. The pooled distribution is\nmultimodal by construction. No transformation fixes this, because there is nothing\npathological to fix — the data is behaving exactly as a three-population sample should.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Compute all three coefficients, pooled and within species\"}\ncoef_row <- function(df, label) {\n  x <- df$bill_length_mm; y <- df$flipper_length_mm\n  data.frame(\n    Group      = label,\n    n          = nrow(df),\n    Pearson    = cor(x, y, method = \"pearson\"),\n    Spearman   = cor(x, y, method = \"spearman\"),\n    Kendall    = cor(x, y, method = \"kendall\")\n  )\n}\n\nby_species <- bind_rows(\n  coef_row(peng, \"All species (pooled)\"),\n  lapply(levels(peng$species), function(s) coef_row(filter(peng, species == s), s))\n)\n\nkable(by_species, digits = 3,\n      caption = \"Bill length vs. flipper length. The pooled estimate is inflated by between-species separation.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Bill length vs. flipper length. The pooled estimate is inflated by between-species separation.\n\n|Group                |   n| Pearson| Spearman| Kendall|\n|:--------------------|---:|-------:|--------:|-------:|\n|All species (pooled) | 342|   0.656|    0.673|   0.483|\n|Adelie               | 151|   0.326|    0.339|   0.227|\n|Chinstrap            |  68|   0.472|    0.533|   0.400|\n|Gentoo               | 123|   0.661|    0.647|   0.470|\n\n\n:::\n:::\n\n\n\nThe pooled $r = 0.656$ is substantially larger than the within-species correlations\n($0.326$, $0.472$, $0.661$). Most of the pooled association is not a within-animal\nrelationship between bill and flipper at all — it is the fact that Gentoos are simply\nbigger than Adélies on both axes. Pooling three clusters manufactures correlation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Show the scatter plot code\"}\nggplot(peng, aes(bill_length_mm, flipper_length_mm)) +\n  geom_smooth(method = \"loess\", formula = y ~ x, se = TRUE,\n              colour = \"grey25\", fill = \"grey85\",\n              linetype = \"dashed\", size = 0.8) +\n  geom_point(aes(colour = species), alpha = 0.75, size = 2) +\n  geom_smooth(aes(colour = species), method = \"lm\", formula = y ~ x,\n              se = FALSE, size = 0.9) +\n  scale_colour_manual(values = pal, name = NULL) +\n  labs(\n    title    = \"Three species, three relationships, one misleading pooled trend\",\n    subtitle = \"Dashed grey: LOESS on pooled data. Solid: per-species linear fits.\",\n    x        = \"Bill length (mm)\",\n    y        = \"Flipper length (mm)\"\n  )\n```\n\n::: {.cell-output-display}\n![Bill length against flipper length. The dashed line is a LOESS fit to the pooled data; the solid coloured lines are per-species linear fits. The pooled trend is steeper than any individual species' trend.](index_files/figure-html/fig-penguins-1.png){#fig-penguins width=768}\n:::\n:::\n\n\n\n### The stratification trap runs deeper than inflation\n\nPooling does not merely exaggerate associations. It can **reverse their sign**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Bill depth vs. body mass, pooled and stratified\"}\nsimpson <- bind_rows(\n  data.frame(Group = \"All species (pooled)\", n = nrow(peng),\n             Pearson = cor(peng$bill_depth_mm, peng$body_mass_g)),\n  lapply(levels(peng$species), function(s) {\n    d <- filter(peng, species == s)\n    data.frame(Group = s, n = nrow(d),\n               Pearson = cor(d$bill_depth_mm, d$body_mass_g))\n  })\n)\n\nkable(simpson, digits = 3,\n      caption = \"Simpson's paradox: bill depth and body mass are negatively correlated overall and positively correlated within every single species.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Simpson's paradox: bill depth and body mass are negatively correlated overall and positively correlated within every single species.\n\n|Group                |   n| Pearson|\n|:--------------------|---:|-------:|\n|All species (pooled) | 342|  -0.472|\n|Adelie               | 151|   0.576|\n|Chinstrap            |  68|   0.604|\n|Gentoo               | 123|   0.719|\n\n\n:::\n:::\n\n\n\nBill depth and body mass correlate at $-0.472$ across the dataset and at $+0.576$,\n$+0.604$, and $+0.719$ *within each species*. Every subgroup shows the opposite of the\naggregate. No choice of coefficient rescues this — swapping Pearson for Kendall changes\nthe number but not the sign reversal. **The fix is the stratification, not the statistic.**\nThis is directly relevant to the project's design, where clinical group is exactly such a\nstratifying variable.\n\n### Why rank-based concordance survives contamination\n\nHere is the practical argument for $\\tau$, stated as an experiment rather than an\nassertion. We inject one impossible observation — a 200 mm bill on a 100 mm flipper, the\nkind of column-swap or decimal-slip a real data-entry pipeline produces — and recompute.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Inject one data-entry error and recompute\"}\nx_clean <- peng$bill_length_mm\ny_clean <- peng$flipper_length_mm\n\n# One implausible record appended to 342 good ones (0.29% contamination).\nx_dirty <- c(x_clean, 200)\ny_dirty <- c(y_clean, 100)\n\nrobustness <- data.frame(\n  Coefficient = c(\"Pearson r\", \"Spearman rho\", \"Kendall tau\"),\n  Clean = c(cor(x_clean, y_clean),\n            cor(x_clean, y_clean, method = \"spearman\"),\n            cor(x_clean, y_clean, method = \"kendall\")),\n  `With 1 bad record` = c(cor(x_dirty, y_dirty),\n                          cor(x_dirty, y_dirty, method = \"spearman\"),\n                          cor(x_dirty, y_dirty, method = \"kendall\")),\n  check.names = FALSE\n) %>%\n  mutate(`% change` = 100 * (`With 1 bad record` - Clean) / Clean)\n\nkable(robustness, digits = c(0, 3, 3, 1),\n      caption = \"One contaminated record in 343. Pearson loses 96% of its signal; the rank measures lose about 2%.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: One contaminated record in 343. Pearson loses 96% of its signal; the rank measures lose about 2%.\n\n|Coefficient  | Clean| With 1 bad record| % change|\n|:------------|-----:|-----------------:|--------:|\n|Pearson r    | 0.656|             0.028|    -95.7|\n|Spearman rho | 0.673|             0.658|     -2.2|\n|Kendall tau  | 0.483|             0.475|     -1.8|\n\n\n:::\n:::\n\n\n\nA single bad row out of 343 destroys **96%** of Pearson's estimate, taking it from\n$+0.656$ to $+0.028$ — from \"strong relationship\" to \"no relationship.\" Kendall's $\\tau$\nmoves by 1.8%.\n\nThe mechanism follows directly from the definitions. Pearson's $r$ is built from\n$\\sum (x_i - \\bar{x})(y_i - \\bar{y})$, so a point far from the centroid contributes a\nterm proportional to its distance in *both* coordinates — its leverage is unbounded.\nKendall's $\\tau$ only ever asks whether each pair agrees in ordering. One aberrant point\nparticipates in exactly $n - 1$ of the $\\binom{n}{2}$ pairs, and no matter how absurd its\nvalue, it can flip at most those $n-1$ pair verdicts. Its influence is bounded by\nconstruction, at roughly $2/n$.\n\nFor this project's data — methylation proportions with heavy tails, coverage-driven\nheteroscedasticity, and occasional sites with wild estimates from thin coverage — that\nbounded-influence property is the whole argument. See\n[the statistician's view of this study](../study-for-statisticians.qmd) for how these\nconcerns propagate into the modelling choices.\n\n## Q: What happens when data takes a shape like the Datasaurus?\n\nThe Datasaurus Dozen [@matejka2017datasaurus] is a set of thirteen datasets that share\ntheir means, standard deviations, and Pearson correlation to two decimal places while\nlooking nothing alike — a modern, deliberately extreme extension of Anscombe's quartet\n[@anscombe1973].\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Load the dinosaur\"}\ndino <- datasaurus_dozen %>% filter(dataset == \"dino\")\ncat(\"Observations:\", nrow(dino), \"| Pairs to examine:\", choose(nrow(dino), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObservations: 142 | Pairs to examine: 10011 \n```\n\n\n:::\n:::\n\n\n\n### Counting concordant and discordant pairs explicitly\n\nRather than calling `cor(method = \"kendall\")`, we implement the definition directly:\na double loop over every pair, classifying each one.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Show the pair-counting algorithm\"}\n#' Count concordant, discordant, and tied pairs by brute force.\n#'\n#' Examines all n(n-1)/2 unordered pairs. Deliberately written as an explicit\n#' loop to mirror the definition; O(n^2) and not intended for large n.\n#'\n#' @return list with C, D, tied-on-x-only, tied-on-y-only, and tied-on-both counts\ncount_cd <- function(x, y) {\n  n <- length(x)\n  C <- 0L; D <- 0L; Tx <- 0L; Ty <- 0L; Txy <- 0L\n\n  for (i in seq_len(n - 1L)) {\n    for (j in (i + 1L):n) {\n      dx <- x[i] - x[j]\n      dy <- y[i] - y[j]\n      s  <- sign(dx) * sign(dy)\n\n      if (s > 0) {\n        C <- C + 1L                      # same ordering on both axes\n      } else if (s < 0) {\n        D <- D + 1L                      # opposite ordering\n      } else if (dx == 0 && dy == 0) {\n        Txy <- Txy + 1L                  # tied on both: informative for neither\n      } else if (dx == 0) {\n        Tx <- Tx + 1L                    # tied on x only\n      } else {\n        Ty <- Ty + 1L                    # tied on y only\n      }\n    }\n  }\n  list(C = C, D = D, Tx = Tx, Ty = Ty, Txy = Txy,\n       n_pairs = n * (n - 1L) / 2L)\n}\n\ncd_dino <- count_cd(dino$x, dino$y)\nstr(cd_dino)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 6\n $ C      : int 4710\n $ D      : int 5191\n $ Tx     : int 54\n $ Ty     : int 56\n $ Txy    : int 0\n $ n_pairs: num 10011\n```\n\n\n:::\n:::\n\n\n\nNow the two forms of Kendall's coefficient. The textbook definition,\n$\\tau_a = (C-D)/(C+D)$, assumes no ties. Real data has ties, and R's `cor()` returns the\ntie-corrected $\\tau_b$:\n\n$$\n\\tau_a = \\frac{C - D}{C + D}\n\\qquad\\qquad\n\\tau_b = \\frac{C - D}{\\sqrt{(C + D + T_x)\\,(C + D + T_y)}}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Kendall's tau, both variants, validated against base R\"}\ntau_a <- function(cd) (cd$C - cd$D) / (cd$C + cd$D)\n\ntau_b <- function(cd) {\n  (cd$C - cd$D) /\n    sqrt((cd$C + cd$D + cd$Tx) * (cd$C + cd$D + cd$Ty))\n}\n\n# Pearson and Spearman rebuilt from their definitions.\npearson_r <- function(x, y) {\n  xc <- x - mean(x); yc <- y - mean(y)\n  sum(xc * yc) / sqrt(sum(xc^2) * sum(yc^2))\n}\n\nspearman_rho <- function(x, y) pearson_r(rank(x), rank(y))\n\n# Validate every hand-written function against the reference implementation.\n# A mismatch aborts the render, so a clean build is proof of correctness.\nstopifnot(\n  all.equal(tau_b(cd_dino),                cor(dino$x, dino$y, method = \"kendall\")),\n  all.equal(pearson_r(dino$x, dino$y),     cor(dino$x, dino$y, method = \"pearson\")),\n  all.equal(spearman_rho(dino$x, dino$y),  cor(dino$x, dino$y, method = \"spearman\"))\n)\n\ncat(\"All hand-written implementations match base R.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll hand-written implementations match base R.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Show the pair-count breakdown\"}\nkable(\n  data.frame(\n    Quantity = c(\"Concordant pairs (C)\", \"Discordant pairs (D)\",\n                 \"Tied on x only\", \"Tied on y only\", \"Total pairs\",\n                 \"tau_a = (C-D)/(C+D)\", \"tau_b (tie-corrected)\"),\n    # Character column: the counts are integers and the taus are not,\n    # so a numeric column would force one shared number format on both.\n    Value = c(format(c(cd_dino$C, cd_dino$D, cd_dino$Tx, cd_dino$Ty,\n                       cd_dino$n_pairs), big.mark = \",\"),\n              sprintf(\"%.4f\", tau_a(cd_dino)),\n              sprintf(\"%.4f\", tau_b(cd_dino)))\n  ),\n  align = c(\"l\", \"r\"),\n  caption = \"The dinosaur's pairs are almost evenly split between agreement and disagreement.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: The dinosaur's pairs are almost evenly split between agreement and disagreement.\n\n|Quantity              |   Value|\n|:---------------------|-------:|\n|Concordant pairs (C)  |   4,710|\n|Discordant pairs (D)  |   5,191|\n|Tied on x only        |      54|\n|Tied on y only        |      56|\n|Total pairs           |  10,011|\n|tau_a = (C-D)/(C+D)   | -0.0486|\n|tau_b (tie-corrected) | -0.0483|\n\n\n:::\n:::\n\n\n\nOut of 10,011 pairs, 4,710 agree on ordering and 5,191 disagree. The near-balance is\nwhat drives $\\tau$ to $-0.048$. Kendall's $\\tau$ is not malfunctioning — it is correctly\nreporting that the dinosaur has no monotone trend. The failure is one of *interpretation*:\nreading \"$\\tau \\approx 0$\" as \"no relationship\" rather than \"no monotone relationship.\"\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Show the dinosaur plot code\"}\nggplot(dino, aes(x, y)) +\n  geom_point(colour = \"#167d78\", alpha = 0.8, size = 2.2) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              colour = \"#b8634f\", size = 1) +\n  geom_smooth(method = \"loess\", formula = y ~ x, se = FALSE,\n              colour = \"#123b5d\", linetype = \"dashed\", size = 1) +\n  labs(\n    title    = \"Obvious structure, invisible to every correlation coefficient\",\n    subtitle = sprintf(\"r = %.3f   rho = %.3f   tau = %.3f\",\n                       cor(dino$x, dino$y),\n                       cor(dino$x, dino$y, method = \"spearman\"),\n                       tau_b(cd_dino)),\n    x = NULL, y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![The dinosaur, with a LOESS fit (dashed) and a linear fit (solid). Both smoothers are essentially flat. Every monotone-association measure reports approximately zero.](index_files/figure-html/fig-dino-1.png){#fig-dino width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Show the small-multiples code\"}\nshown <- c(\"dino\", \"star\", \"circle\", \"bullseye\", \"x_shape\", \"slant_up\")\n\ndatasaurus_dozen %>%\n  filter(dataset %in% shown) %>%\n  mutate(dataset = factor(dataset, levels = shown)) %>%\n  ggplot(aes(x, y)) +\n  geom_point(colour = \"#167d78\", alpha = 0.75, size = 1.4) +\n  facet_wrap(~dataset, ncol = 3) +\n  labs(title = \"Same mean, same SD, same correlation\", x = NULL, y = NULL) +\n  theme(axis.text = element_blank())\n```\n\n::: {.cell-output-display}\n![Six members of the Datasaurus Dozen. Their summary statistics agree to two decimal places; their shapes do not.](index_files/figure-html/fig-dozen-1.png){#fig-dozen width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Confirm the summary statistics really are identical\"}\ndatasaurus_dozen %>%\n  filter(dataset %in% shown) %>%\n  group_by(dataset) %>%\n  summarise(\n    `mean x` = mean(x), `mean y` = mean(y),\n    `sd x`   = sd(x),   `sd y`   = sd(y),\n    `r`      = cor(x, y),\n    `tau`    = cor(x, y, method = \"kendall\"),\n    .groups  = \"drop\"\n  ) %>%\n  arrange(match(dataset, shown)) %>%\n  kable(digits = 2, caption = \"Identical to two decimals on every classical summary. Kendall's tau is equally uninformative here — it is a monotone-association measure, not a shape detector.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Identical to two decimals on every classical summary. Kendall's tau is equally uninformative here — it is a monotone-association measure, not a shape detector.\n\n|dataset  | mean x| mean y|  sd x|  sd y|     r|   tau|\n|:--------|------:|------:|-----:|-----:|-----:|-----:|\n|dino     |  54.26|  47.83| 16.77| 26.94| -0.06| -0.05|\n|star     |  54.27|  47.84| 16.77| 26.93| -0.06| -0.03|\n|circle   |  54.27|  47.84| 16.76| 26.93| -0.07| -0.02|\n|bullseye |  54.27|  47.83| 16.77| 26.94| -0.07| -0.05|\n|x_shape  |  54.26|  47.84| 16.77| 26.93| -0.07| -0.03|\n|slant_up |  54.27|  47.83| 16.77| 26.94| -0.07| -0.03|\n\n\n:::\n:::\n\n\n\n### Measures that see arbitrary dependence — and their bias floor\n\nTo detect the dinosaur we need measures of *general* association. Two standard choices,\nboth implemented here from their definitions.\n\n**Distance correlation** [@szekely2007dcor; see also @reshef2011mic for the surrounding\nliterature] replaces covariance of values with covariance of pairwise *distances*.\nDouble-centre the two distance matrices, and the resulting statistic is zero if and only\nif the variables are independent — in the population.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Distance correlation from scratch\"}\n#' Szekely-Rizzo distance correlation (the V-statistic form).\ndcor_manual <- function(x, y) {\n  A <- as.matrix(dist(x))\n  B <- as.matrix(dist(y))\n\n  # Double-centre: subtract row means, column means, add back the grand mean.\n  double_centre <- function(M) {\n    M - rowMeans(M)[row(M)] - colMeans(M)[col(M)] + mean(M)\n  }\n  A <- double_centre(A)\n  B <- double_centre(B)\n\n  n     <- length(x)\n  dcov2 <- sum(A * B) / n^2      # squared distance covariance\n  dvarx <- sum(A * A) / n^2\n  dvary <- sum(B * B) / n^2\n\n  sqrt(dcov2) / sqrt(sqrt(dvarx * dvary))\n}\n\n# Sanity checks on cases with known answers.\nt_grid <- seq(-1, 1, length.out = 200)\n\n# Draw the independent noise ONCE, so both coefficients describe the same data.\nnoise_x <- rnorm(200)\nnoise_y <- rnorm(200)\n\ncases <- list(\n  \"Perfect linear: y = 2x + 3\" = list(t_grid, 2 * t_grid + 3),\n  \"Parabola: y = x^2\"          = list(t_grid, t_grid^2),\n  \"Circle\"                     = list(cos(pi * t_grid), sin(pi * t_grid)),\n  \"Independent noise\"          = list(noise_x, noise_y)\n)\n\nkable(\n  data.frame(\n    Case    = names(cases),\n    Pearson = sapply(cases, function(p) cor(p[[1]], p[[2]])),\n    dCor    = sapply(cases, function(p) dcor_manual(p[[1]], p[[2]])),\n    row.names = NULL\n  ),\n  digits = 3,\n  caption = \"Distance correlation recovers non-monotone structure that Pearson misses. Note the last row: under genuine independence dCor is NOT zero.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Distance correlation recovers non-monotone structure that Pearson misses. Note the last row: under genuine independence dCor is NOT zero.\n\n|Case                       | Pearson|  dCor|\n|:--------------------------|-------:|-----:|\n|Perfect linear: y = 2x + 3 |   1.000| 1.000|\n|Parabola: y = x^2          |   0.000| 0.491|\n|Circle                     |   0.000| 0.198|\n|Independent noise          |   0.008| 0.124|\n\n\n:::\n:::\n\n\n\nThat final row is the warning. The two variables are genuinely independent, Pearson\ncorrectly reports essentially zero — and dCor does not. The V-statistic estimator is\n**positively biased**: it is bounded below by zero, so sampling noise can only push it\nupward, and it approaches zero only asymptotically. Any dCor value must therefore be read\nagainst its own null, never against zero.\n\n**Mutual information** measures dependence in bits, comparing the joint distribution\nagainst the product of the marginals:\n\n$$I(X;Y) = \\sum_{x}\\sum_{y} p(x,y)\\, \\log_2 \\frac{p(x,y)}{p(x)\\,p(y)}$$\n\nFor continuous data it requires discretisation, and the choice of bin count matters\nenormously.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Histogram mutual information, with a bin-sensitivity sweep\"}\n#' Plug-in mutual information via equal-width binning, in bits.\nmutual_info <- function(x, y, bins = 8L) {\n  bx  <- cut(x, breaks = bins, labels = FALSE)\n  by  <- cut(y, breaks = bins, labels = FALSE)\n  pxy <- table(bx, by) / length(x)      # joint\n  px  <- rowSums(pxy)                   # marginals\n  py  <- colSums(pxy)\n  indep <- outer(px, py)                # what we'd see under independence\n  nz  <- pxy > 0                        # 0 log 0 := 0\n  sum(pxy[nz] * log2(pxy[nz] / indep[nz]))\n}\n\n# Compare the dinosaur against a shuffled version of itself. Shuffling y\n# destroys any dependence while preserving both marginal distributions,\n# so it is the correct null for this comparison.\nsweep <- lapply(c(4, 6, 8, 10, 12, 16), function(b) {\n  null_mi <- mean(replicate(200, mutual_info(dino$x, sample(dino$y), b)))\n  data.frame(\n    Bins            = b,\n    `MI (observed)` = mutual_info(dino$x, dino$y, b),\n    `MI (shuffled)` = null_mi,\n    Excess          = mutual_info(dino$x, dino$y, b) - null_mi,\n    check.names     = FALSE\n  )\n}) %>% bind_rows()\n\nkable(sweep, digits = 3,\n      caption = \"Raw MI rises with bin count for BOTH the real data and the shuffled null. Only the excess over the null is interpretable.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Raw MI rises with bin count for BOTH the real data and the shuffled null. Only the excess over the null is interpretable.\n\n| Bins| MI (observed)| MI (shuffled)| Excess|\n|----:|-------------:|-------------:|------:|\n|    4|         0.177|         0.047|  0.131|\n|    6|         0.357|         0.145|  0.212|\n|    8|         0.526|         0.291|  0.235|\n|   10|         0.704|         0.475|  0.229|\n|   12|         0.955|         0.682|  0.273|\n|   16|         1.303|         1.084|  0.219|\n\n\n:::\n:::\n\n\n\nRaw mutual information climbs steadily with bin count — but so does the mutual\ninformation of data with all dependence destroyed. At 16 bins, shuffled data scores\nhigher than the real data did at 8 bins. **A raw MI value is close to meaningless without\nits null.** The excess column is the interpretable quantity, and it peaks in the middle of\nthe range.\n\n### Calibrating against a permutation null\n\nBoth general-association measures have bias floors, so both need calibration. A\npermutation test supplies it without distributional assumptions: shuffle $y$, recompute,\nrepeat, and ask where the observed value falls in that null distribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Permutation test for all four measures\"}\nperm_test <- function(x, y, stat_fn, B = 999) {\n  observed <- stat_fn(x, y)\n  null_dist <- replicate(B, stat_fn(x, sample(y)))\n  # +1 in numerator and denominator: the observed value is one valid arrangement.\n  list(observed = observed,\n       null_mean = mean(null_dist),\n       p_value  = (sum(null_dist >= observed) + 1) / (B + 1))\n}\n\nmeasures <- list(\n  \"Pearson |r|\"          = function(x, y) abs(cor(x, y)),\n  \"Spearman |rho|\"       = function(x, y) abs(cor(x, y, method = \"spearman\")),\n  \"Kendall |tau|\"        = function(x, y) abs(cor(x, y, method = \"kendall\")),\n  \"Distance correlation\" = dcor_manual,\n  \"Mutual information\"   = function(x, y) mutual_info(x, y, bins = 8L)\n)\n\nresults <- lapply(names(measures), function(nm) {\n  r <- perm_test(dino$x, dino$y, measures[[nm]], B = 999)\n  data.frame(\n    Measure        = nm,\n    Observed       = r$observed,\n    `Null mean`    = r$null_mean,\n    `p-value`      = r$p_value,\n    check.names    = FALSE\n  )\n}) %>% bind_rows()\n\nkable(results, digits = c(0, 4, 4, 4),\n      caption = \"Permutation test on the dinosaur, B = 999. Only mutual information detects the structure at this sample size.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Permutation test on the dinosaur, B = 999. Only mutual information detects the structure at this sample size.\n\n|Measure                  | Observed| Null mean| p-value|\n|:------------------------|--------:|---------:|-------:|\n|Pearson &#124;r&#124;    |   0.0645|    0.0655|   0.439|\n|Spearman &#124;rho&#124; |   0.0651|    0.0673|   0.435|\n|Kendall &#124;tau&#124;  |   0.0483|    0.0458|   0.392|\n|Distance correlation     |   0.1645|    0.1384|   0.169|\n|Mutual information       |   0.5262|    0.2822|   0.001|\n\n\n:::\n:::\n\n\n\nThis table is the honest result, and it is more interesting than the tidy story:\n\n- **Pearson, Spearman, and Kendall are blind**, exactly as predicted. Their $p$-values\n  sit near $0.4$–$0.5$ — entirely consistent with independence.\n- **Mutual information detects the dinosaur decisively**, with $p \\approx 0.001$. Its\n  observed value sits far above its own null mean.\n- **Distance correlation does *not* reach significance** at $n = 142$, despite an\n  observed value of $0.16$ that looks encouraging in isolation. Its null mean is nearly\n  as large. Reporting \"dCor $= 0.16$\" without the permutation test would have been an\n  unsupported claim.\n\nThe dCor result deserves emphasis because it contradicts the tidy version of this story\nusually told. Distance correlation is consistent against all dependence *asymptotically*;\nat 142 points, against a shape whose marginals are engineered to look ordinary, it does\nnot have the power. **Consistency is not power.**\n\n::: {.callout-note title=\"On the Maximal Information Coefficient\"}\nMIC [@reshef2011mic] searches over grid resolutions and reports the best normalised\nmutual information, aiming for a measure that scores diverse relationship types on a\ncomparable scale. The R implementation is the `minerva` package. It is cited here rather\nthan computed: it requires a compiled dependency, and the bin-sweep above already makes\nthe underlying point — the grid resolution is a free parameter, and any statistic that\noptimises over it needs its own null calibration just as much as plain MI does. MIC has\nalso drawn substantive criticism on statistical-power grounds, so it is not a drop-in\nupgrade.\n:::\n\n## Q: Can I watch a coefficient break in real time?\n\nStatic tables make the argument; watching it happen makes it stick. The widget below\ncarries the real datasets used in this post — the Datasaurus shapes, the penguin\nmorphometrics, and two synthetic controls — and recomputes Pearson's $r$, Spearman's\n$\\rho$, and Kendall's $\\tau_b$ in the browser, along with the raw concordant and\ndiscordant pair counts.\n\n**Click anywhere on the plot to add an outlier.** Watch which coefficients survive it.\n\n\n\n\n```{.r .cell-code  code-summary=\"Show how the widget's data is exported\"}\n# Export the genuine datasets to the browser. Nothing here is hand-typed:\n# each series is the same data analysed in the sections above.\nwidget_sets <- list()\n\nfor (shape in c(\"dino\", \"circle\", \"star\", \"x_shape\", \"slant_up\")) {\n  d <- datasaurus_dozen[datasaurus_dozen$dataset == shape, ]\n  widget_sets[[shape]] <- list(\n    label = shape, x = round(d$x, 3), y = round(d$y, 3),\n    xlab = \"x\", ylab = \"y\"\n  )\n}\n\nwidget_sets[[\"penguins\"]] <- list(\n  label = \"penguins\", x = peng$bill_length_mm, y = peng$flipper_length_mm,\n  xlab = \"Bill length (mm)\", ylab = \"Flipper length (mm)\"\n)\n\n# Two synthetic controls with known answers, for calibration by eye.\ntt <- seq(-1, 1, length.out = 120)\nwidget_sets[[\"linear\"]] <- list(\n  label = \"linear + noise\",\n  x = round(tt, 3), y = round(2 * tt + rnorm(120, 0, 0.35), 3),\n  xlab = \"x\", ylab = \"y\"\n)\nwidget_sets[[\"parabola\"]] <- list(\n  label = \"parabola\",\n  x = round(tt, 3), y = round(tt^2 + rnorm(120, 0, 0.05), 3),\n  xlab = \"x\", ylab = \"y\"\n)\n\ncat(\"<script>window.CORR_DATA = \",\n    jsonlite::toJSON(widget_sets, auto_unbox = TRUE, digits = 6),\n    \";</script>\", sep = \"\")\n```\n\n<script>window.CORR_DATA = {\"dino\":{\"label\":\"dino\",\"x\":[55.385,51.538,46.154,42.821,40.769,38.718,35.641,33.077,28.974,26.154,23.077,22.308,22.308,23.333,25.897,29.487,32.821,35.385,40.256,44.103,46.667,50,53.077,56.667,59.231,61.282,61.538,61.795,57.436,54.872,52.564,48.205,49.487,51.026,45.385,42.821,38.718,35.128,32.564,30,33.59,36.667,38.205,29.744,29.744,30,32.051,35.897,41.026,44.103,47.179,49.487,51.538,53.59,55.128,56.667,59.231,62.308,64.872,67.949,70.513,71.538,71.538,69.487,46.923,48.205,50,53.077,55.385,56.667,56.154,53.846,51.282,50,47.949,29.744,29.744,31.282,57.949,61.795,64.872,68.462,70.769,72.051,73.846,75.128,76.667,77.692,79.744,81.795,83.333,85.128,86.41,87.949,89.487,93.333,95.385,98.205,56.667,59.231,60.769,63.077,64.103,64.359,74.359,71.282,67.949,65.897,63.077,61.282,58.718,55.128,52.308,49.744,47.436,44.872,48.718,51.282,54.103,56.154,52.051,48.718,47.179,46.154,50.513,53.846,57.436,60,64.103,66.923,71.282,74.359,78.205,67.949,68.462,68.205,37.692,39.487,91.282,50,47.949,44.103],\"y\":[97.18,96.026,94.487,91.41,88.333,84.872,79.872,77.564,74.487,71.41,66.41,61.795,57.179,52.949,51.026,51.026,51.026,51.41,51.41,52.949,54.103,55.256,55.641,56.026,57.949,62.179,66.41,69.103,55.256,49.872,46.026,38.333,42.179,44.103,36.41,32.564,31.41,30.256,32.179,36.795,41.41,45.641,49.103,36.026,32.179,29.103,26.795,25.256,25.256,25.641,28.718,31.41,34.872,37.564,40.641,42.179,44.487,46.026,46.795,47.949,53.718,60.641,64.487,69.487,79.872,84.103,85.256,85.256,86.026,86.026,82.949,80.641,78.718,78.718,77.564,59.872,62.179,62.564,99.487,99.103,97.564,94.103,91.026,86.41,83.333,79.103,75.256,71.41,66.795,60.256,55.256,51.41,47.564,46.026,42.564,39.872,36.795,33.718,40.641,38.333,33.718,29.103,25.256,24.103,22.949,22.949,22.18,20.256,19.103,19.103,18.333,18.333,18.333,17.564,16.026,13.718,14.872,14.872,14.872,14.103,12.564,11.026,9.872,6.026,9.487,10.256,10.256,10.641,10.641,10.641,10.641,10.641,10.641,8.718,5.256,2.949,25.769,25.385,41.538,95.769,95,92.692],\"xlab\":\"x\",\"ylab\":\"y\"},\"circle\":{\"label\":\"circle\",\"x\":[55.993,50.032,51.288,51.171,44.378,45.01,48.56,42.142,41.027,34.575,31.169,32.644,26.667,26.459,25.538,26.321,26.163,25.214,26.86,31.761,39.793,45.617,53.771,56.451,66.094,56.926,58.988,57.902,64.813,60.35,48.891,47.55,30.889,28.973,35.161,45.87,32.831,39.486,33.446,21.864,25.166,22.959,25.586,26.314,33.037,36.469,26.514,36.027,42.681,45.041,47.352,53.846,55.13,52.188,58.673,82.144,75.687,85.345,83.845,85.665,77.931,73.032,70.103,57.145,46.962,50.565,53.72,54.2,47.875,51.473,52.751,48.562,53.081,56.475,49.571,37.628,32.264,32.542,52.825,58.528,56.266,57.076,54.256,62.686,68.086,65.118,68.746,63.09,77.205,82.034,81.578,85.18,84.287,85.622,85.604,84.425,85.571,84.627,73.396,73.507,63.356,72.959,64.021,61.124,75.674,69.514,58.572,70.982,65.223,65.315,64.01,57.141,56.365,43.046,52.082,42.879,51.567,58.839,60.756,54.761,53.57,48.915,52.646,49.838,52.684,65.807,60.674,63.395,64.802,65.026,65.756,69.968,68.893,61.827,60.788,61.916,45.029,39.921,84.794,55.663,50.492,51.467],\"y\":[79.277,79.013,82.436,79.165,78.165,77.881,78.788,76.881,76.41,72.725,69.245,70.733,62.981,62.635,60.63,62.396,62.027,60.273,63.142,69.798,75.808,78.12,79.303,79.247,77.018,79.206,78.917,79.081,77.487,78.729,16.807,17.071,26.329,29.05,22.787,17.489,24.798,20.033,24.191,46.053,35.767,51.288,60.847,33.297,24.564,21.876,32.919,22.195,18.543,17.735,17.135,16.387,16.353,16.418,16.663,33.195,24.742,52.886,58.616,45.543,68.69,73.121,75.683,79.194,78.667,79.077,79.307,79.325,78.676,79.16,79.294,78.782,79.297,79.168,79.038,74.558,70.317,70.702,85.578,78.979,79.253,79.194,79.314,78.175,76.112,77.399,75.79,78.041,69.312,62.682,63.895,53.782,57.256,45.024,50.762,38.761,44.56,39.487,22.816,22.857,17.724,22.511,17.884,17.116,24.783,20.279,16.643,21.146,18.397,18.334,17.924,16.599,16.327,18.403,16.454,18.489,16.486,16.638,17.033,16.366,16.34,16.799,16.385,16.676,16.408,18.141,17.052,17.701,18.217,18.288,18.516,20.539,20.032,17.27,17.046,17.282,17.724,19.702,55.569,83.356,78.998,79.202],\"xlab\":\"x\",\"ylab\":\"y\"},\"star\":{\"label\":\"star\",\"x\":[58.214,58.196,58.718,57.278,58.082,57.489,28.089,28.085,28.087,27.578,27.78,28.589,28.739,27.025,28.801,27.186,29.285,39.403,28.811,34.304,29.603,49.116,39.618,43.233,64.893,62.49,68.988,62.106,32.462,41.327,44.007,44.074,44.001,45.006,44.444,42.179,44.045,41.64,41.938,44.054,39.207,28.704,31.709,42.812,43.301,40.399,40.436,40.937,39.662,40.899,41.969,40.383,56.538,52.971,54.621,65.099,63.056,70.96,69.896,70.596,69.647,77.393,64.401,63.869,56.594,56.531,59.652,56.637,58.672,58.222,57.915,55.316,54.576,54.413,55.075,29.433,29.423,29.006,58.462,57.998,57.549,59.53,58.249,58.025,58.382,62.567,72.176,79.473,80.358,78.757,82.54,86.436,79.489,81.53,79.187,77.899,75.131,76.058,57.615,56.171,66.288,67.882,64.028,77.497,77.635,77.864,77.338,76.18,77.253,77.413,76.732,49.471,42.477,43.595,50.34,40.749,38.387,38.404,38.764,41.47,47.155,39.583,41.74,39.312,41.68,39.087,41.482,77.606,75.983,76.946,77.544,77.585,76.822,77.349,77.573,77.973,41.529,43.723,79.326,56.664,57.822,58.243],\"y\":[91.882,92.215,90.311,89.908,92.008,88.085,63.511,63.59,63.123,62.821,63.518,63.024,62.721,62.902,63.389,63.559,63.384,51.151,61.358,56.542,60.157,63.66,62.925,63.165,65.814,74.584,63.232,75.991,62.882,49.07,46.45,34.553,33.904,38.299,36.019,26.492,35.662,27.093,24.992,33.556,51.534,61.778,58.838,30.02,31.526,16.347,20.233,16.913,15.609,20.799,26.497,21.391,32.444,29.04,30.345,27.242,29.709,41.26,43.454,41.965,44.044,63.371,67.449,70.214,86.927,87.5,87.809,85.637,90.077,90.411,89.954,80.252,77.536,78.229,79.818,60.802,63.068,63.391,90.265,92.16,90.749,88.327,92.13,91.694,90.553,77.744,63.129,63.409,63.295,53.333,56.541,59.793,53.652,56.025,53.235,51.822,23.372,16.384,33.822,32.118,26.117,24.236,27.673,14.949,14.462,14.611,15.89,15.913,15.152,15.222,16.217,25.063,18.338,19.994,26.471,16.182,14.58,14.452,14.366,17.278,22.378,17.648,17.829,15.641,17.746,15.122,18.047,15.163,16.307,15.858,15.254,15.83,15.595,15.775,14.781,14.956,24.916,19.077,52.9,87.94,90.693,92.104],\"xlab\":\"x\",\"ylab\":\"y\"},\"x_shape\":{\"label\":\"x_shape\",\"x\":[38.338,35.752,32.767,33.73,37.238,36.027,39.239,39.785,35.166,40.622,39.182,42.431,43.081,44.361,44.325,47.552,48.665,46.281,50.563,52.631,54.636,51.346,57.135,54.171,50.942,66.513,64.398,68.687,65.028,53.305,52.945,45.226,50.843,49.659,47.143,41.27,47.13,40.916,38.66,42.613,41.209,50.649,52.132,39.797,43.55,36.715,37.225,40.512,40.222,44.125,42.346,44.189,45.814,46.643,52.19,51.1,65.401,64.852,63.404,65.372,61.908,71.827,72.655,76.889,43.745,39.054,39.932,39.763,41.323,41.787,39.756,40.75,43.857,42.368,39.463,44.517,41.636,45.423,42.003,76.106,79.203,84.848,81.564,85.446,80.312,80.766,82.67,77.164,74.071,74.114,68.942,73.242,71.867,71.569,71.483,78.129,78.79,77.782,48.531,65.531,70.118,70.472,76.791,72.409,76.271,76.953,75.108,75.969,75.284,77.052,42.827,42.081,39.878,36.475,37.103,34.149,37.579,41.064,42.195,36.606,39.431,37.562,34.238,34.141,36.659,40.644,36.792,75.948,76.841,81.95,81.644,84.61,84.103,80.18,80.573,79.004,40.048,34.795,79.222,36.031,34.5,31.107],\"y\":[92.473,94.117,88.518,88.622,83.725,82.041,79.264,82.261,84.156,78.542,79.819,75.134,75.347,70.474,71.046,66.46,64.961,68.028,62.624,59.964,57.494,61.601,53.878,58.06,62.097,59.071,56.175,62.237,57.096,40.884,40.385,30.555,37.745,36.273,32.025,21.722,31.31,23.542,21.69,24.195,24.129,37.484,39.365,16.084,24.307,17.382,17.98,22.962,20.615,23.366,24.558,28.773,31.057,31.407,39.368,38.096,42.614,43.134,44.847,42.696,53.19,65.686,66.878,72.165,71.268,83.119,79.939,76.406,80.212,83.988,79.657,77.205,77.61,73.638,78.46,70.369,76.249,69.096,97.838,95.305,92.407,95.425,83.793,83.078,76.516,79.896,81.711,73.524,68.48,71.926,62.635,67.353,34.329,34.699,34.681,23.139,25.597,23.447,34.152,42.281,36.448,36.088,28.072,33.039,25.57,27.771,30.017,29.039,24.875,27.906,25.557,24.947,18.325,17.719,15.446,13.524,15.016,12.214,20.919,15.749,19.324,11.928,13.713,4.578,17.682,20.241,13.392,22.745,20.919,19.875,16.592,14.248,8.981,19.089,8.366,10.628,24.261,13.97,22.095,93.122,86.61,89.462],\"xlab\":\"x\",\"ylab\":\"y\"},\"slant_up\":{\"label\":\"slant_up\",\"x\":[47.695,44.61,43.856,41.579,49.177,42.652,30.123,31.916,27.888,27.548,20.21,24.443,24.631,21.038,27.106,28.09,31.136,37.701,43.393,51.262,43.287,55.906,50.199,55.762,58.323,70.171,60.6,63.76,54.389,55.241,49.07,46.018,44.76,51.601,36.466,33.395,37.58,36.62,36.163,33.168,42.645,47.225,48.392,27.245,30.404,30.081,33.981,34.251,51.141,49.9,55.59,55.482,63.573,59.025,62.424,47.85,52.269,68.851,65.676,77.747,80.353,60.338,61.659,71.545,49.041,51.887,57.969,54.856,54.133,51.309,61.12,55.564,55.044,50.444,43.828,37.791,29.293,32.192,51.434,67.464,65.151,65.583,69.289,81.269,78.576,74.187,72.622,75.142,75.169,85.324,84.091,86.256,92.549,90.343,85.819,90.442,92.018,95.261,41.29,66.431,63.986,61.27,60.749,64.655,68.638,65.777,71.134,63.723,73.001,72.437,68.413,52.858,53.53,50.76,42.535,41.53,46.715,48.451,59.633,61.619,48.834,45.343,42.415,58.935,60.684,54.812,61.587,59.716,58.416,59.244,56.594,68.493,65.006,63.921,53.513,57.833,31.033,31.333,86.402,47.442,46.265,40.164],\"y\":[95.241,93.076,94.086,90.304,96.611,90.561,81.144,79.79,75.446,75.165,67.517,54.474,53.396,49.829,54.72,60.512,61.432,68.418,43.598,49.667,43.057,54.253,52.225,54.031,60.031,70.282,59.753,61.186,53.812,52.594,48.897,46.258,41.975,50.032,35.524,35.017,38.832,36.811,33.819,31.248,40.154,44.576,50.332,29.82,29.08,27.588,35.033,34.442,20.618,19.564,26.299,22.827,32.939,28.322,33.487,48.557,52.805,39.573,35.109,47.372,47.8,63.035,64.1,72.658,77.363,80.114,85.356,83.783,83.794,80.136,88.704,85.81,83.541,78.196,71.047,66.855,59.792,60.201,99.257,96,92.503,93.517,99.58,80.636,76.816,74.344,74.527,73.82,73.9,55.389,56.302,55.831,42.902,37.78,37.571,40.133,39.918,46.009,42.312,36.536,32.713,29.386,28.052,16.612,18.508,16.788,19.386,14.521,24.074,20.578,19.913,20.235,24.242,18.089,10.17,13.396,15.613,16.212,7.058,13.411,17.726,13.909,11.694,9.369,10.633,6.57,11.028,11.519,5.646,10.54,8.917,17.987,15.913,15.621,5.875,9.222,28.928,32.539,38.747,98.184,94.116,87.449],\"xlab\":\"x\",\"ylab\":\"y\"},\"penguins\":{\"label\":\"penguins\",\"x\":[39.1,39.5,40.3,36.7,39.3,38.9,39.2,34.1,42,37.8,37.8,41.1,38.6,34.6,36.6,38.7,42.5,34.4,46,37.8,37.7,35.9,38.2,38.8,35.3,40.6,40.5,37.9,40.5,39.5,37.2,39.5,40.9,36.4,39.2,38.8,42.2,37.6,39.8,36.5,40.8,36,44.1,37,39.6,41.1,37.5,36,42.3,39.6,40.1,35,42,34.5,41.4,39,40.6,36.5,37.6,35.7,41.3,37.6,41.1,36.4,41.6,35.5,41.1,35.9,41.8,33.5,39.7,39.6,45.8,35.5,42.8,40.9,37.2,36.2,42.1,34.6,42.9,36.7,35.1,37.3,41.3,36.3,36.9,38.3,38.9,35.7,41.1,34,39.6,36.2,40.8,38.1,40.3,33.1,43.2,35,41,37.7,37.8,37.9,39.7,38.6,38.2,38.1,43.2,38.1,45.6,39.7,42.2,39.6,42.7,38.6,37.3,35.7,41.1,36.2,37.7,40.2,41.4,35.2,40.6,38.8,41.5,39,44.1,38.5,43.1,36.8,37.5,38.1,41.1,35.6,40.2,37,39.7,40.2,40.6,32.1,40.7,37.3,39,39.2,36.6,36,37.8,36,41.5,46.1,50,48.7,50,47.6,46.5,45.4,46.7,43.3,46.8,40.9,49,45.5,48.4,45.8,49.3,42,49.2,46.2,48.7,50.2,45.1,46.5,46.3,42.9,46.1,44.5,47.8,48.2,50,47.3,42.8,45.1,59.6,49.1,48.4,42.6,44.4,44,48.7,42.7,49.6,45.3,49.6,50.5,43.6,45.5,50.5,44.9,45.2,46.6,48.5,45.1,50.1,46.5,45,43.8,45.5,43.2,50.4,45.3,46.2,45.7,54.3,45.8,49.8,46.2,49.5,43.5,50.7,47.7,46.4,48.2,46.5,46.4,48.6,47.5,51.1,45.2,45.2,49.1,52.5,47.4,50,44.9,50.8,43.4,51.3,47.5,52.1,47.5,52.2,45.5,49.5,44.5,50.8,49.4,46.9,48.4,51.1,48.5,55.9,47.2,49.1,47.3,46.8,41.7,53.4,43.3,48.1,50.5,49.8,43.5,51.5,46.2,55.1,44.5,48.8,47.2,46.8,50.4,45.2,49.9,46.5,50,51.3,45.4,52.7,45.2,46.1,51.3,46,51.3,46.6,51.7,47,52,45.9,50.5,50.3,58,46.4,49.2,42.4,48.5,43.2,50.6,46.7,52,50.5,49.5,46.4,52.8,40.9,54.2,42.5,51,49.7,47.5,47.6,52,46.9,53.5,49,46.2,50.9,45.5,50.9,50.8,50.1,49,51.5,49.8,48.1,51.4,45.7,50.7,42.5,52.2,45.2,49.3,50.2,45.6,51.9,46.8,45.7,55.8,43.5,49.6,50.8,50.2],\"y\":[181,186,195,193,190,181,195,193,190,186,180,182,191,198,185,195,197,184,194,174,180,189,185,180,187,183,187,172,180,178,178,188,184,195,196,190,180,181,184,182,195,186,196,185,190,182,179,190,191,186,188,190,200,187,191,186,193,181,194,185,195,185,192,184,192,195,188,190,198,190,190,196,197,190,195,191,184,187,195,189,196,187,193,191,194,190,189,189,190,202,205,185,186,187,208,190,196,178,192,192,203,183,190,193,184,199,190,181,197,198,191,193,197,191,196,188,199,189,189,187,198,176,202,186,199,191,195,191,210,190,197,193,199,187,190,191,200,185,193,193,187,188,190,192,185,190,184,195,193,187,201,211,230,210,218,215,210,211,219,209,215,214,216,214,213,210,217,210,221,209,222,218,215,213,215,215,215,216,215,210,220,222,209,207,230,220,220,213,219,208,208,208,225,210,216,222,217,210,225,213,215,210,220,210,225,217,220,208,220,208,224,208,221,214,231,219,230,214,229,220,223,216,221,221,217,216,230,209,220,215,223,212,221,212,224,212,228,218,218,212,230,218,228,212,224,214,226,216,222,203,225,219,228,215,228,216,215,210,219,208,209,216,229,213,230,217,230,217,222,214,215,222,212,213,192,196,193,188,197,198,178,197,195,198,193,194,185,201,190,201,197,181,190,195,181,191,187,193,195,197,200,200,191,205,187,201,187,203,195,199,195,210,192,205,210,187,196,196,196,201,190,212,187,198,199,201,193,203,187,197,191,203,202,194,206,189,195,207,202,193,210,198],\"xlab\":\"Bill length (mm)\",\"ylab\":\"Flipper length (mm)\"},\"linear\":{\"label\":\"linear + noise\",\"x\":[-1,-0.983,-0.966,-0.95,-0.933,-0.916,-0.899,-0.882,-0.866,-0.849,-0.832,-0.815,-0.798,-0.782,-0.765,-0.748,-0.731,-0.714,-0.697,-0.681,-0.664,-0.647,-0.63,-0.613,-0.597,-0.58,-0.563,-0.546,-0.529,-0.513,-0.496,-0.479,-0.462,-0.445,-0.429,-0.412,-0.395,-0.378,-0.361,-0.345,-0.328,-0.311,-0.294,-0.277,-0.261,-0.244,-0.227,-0.21,-0.193,-0.176,-0.16,-0.143,-0.126,-0.109,-0.092,-0.076,-0.059,-0.042,-0.025,-0.008,0.008,0.025,0.042,0.059,0.076,0.092,0.109,0.126,0.143,0.16,0.176,0.193,0.21,0.227,0.244,0.261,0.277,0.294,0.311,0.328,0.345,0.361,0.378,0.395,0.412,0.429,0.445,0.462,0.479,0.496,0.513,0.529,0.546,0.563,0.58,0.597,0.613,0.63,0.647,0.664,0.681,0.697,0.714,0.731,0.748,0.765,0.782,0.798,0.815,0.832,0.849,0.866,0.882,0.899,0.916,0.933,0.95,0.966,0.983,1],\"y\":[-1.741,-1.888,-2.255,-1.405,-1.962,-1.531,-1.737,-1.302,-1.749,-1.48,-1.205,-1.185,-0.736,-1.91,-1.059,-1.595,-1.031,-1.641,-0.943,-1.781,-1.474,-1.572,-1.354,-1.344,-0.825,-0.882,-0.895,-0.725,-0.792,-1.237,-0.75,-0.845,-1.665,-0.719,-1.013,-0.977,-0.651,-0.338,-0.615,-0.848,-1.094,0.089,-0.452,-0.804,-0.069,0.018,-0.361,-0.506,-0.551,0.084,-0.449,0.008,-0.128,-0.292,-0.188,-0.274,0.285,0.6,-0.295,0.192,-0.44,-0.243,-0.008,0.245,-0.002,-0.208,1.088,0.601,0.419,0.399,0.246,0.539,0.312,-0.199,0.433,0.459,0.639,-0.48,0.825,0.82,1.326,0.533,0.7,1.095,0.223,0.333,1.047,1.018,1.08,0.381,1.526,0.712,1.32,1.274,1.157,1.176,1.222,1.602,1.882,1.353,2.032,1.542,1.729,2.06,1.26,1.935,1.617,1.395,1.669,1.663,1.438,2.073,1.909,1.531,1.872,1.985,1.651,1.851,2.296,2.185],\"xlab\":\"x\",\"ylab\":\"y\"},\"parabola\":{\"label\":\"parabola\",\"x\":[-1,-0.983,-0.966,-0.95,-0.933,-0.916,-0.899,-0.882,-0.866,-0.849,-0.832,-0.815,-0.798,-0.782,-0.765,-0.748,-0.731,-0.714,-0.697,-0.681,-0.664,-0.647,-0.63,-0.613,-0.597,-0.58,-0.563,-0.546,-0.529,-0.513,-0.496,-0.479,-0.462,-0.445,-0.429,-0.412,-0.395,-0.378,-0.361,-0.345,-0.328,-0.311,-0.294,-0.277,-0.261,-0.244,-0.227,-0.21,-0.193,-0.176,-0.16,-0.143,-0.126,-0.109,-0.092,-0.076,-0.059,-0.042,-0.025,-0.008,0.008,0.025,0.042,0.059,0.076,0.092,0.109,0.126,0.143,0.16,0.176,0.193,0.21,0.227,0.244,0.261,0.277,0.294,0.311,0.328,0.345,0.361,0.378,0.395,0.412,0.429,0.445,0.462,0.479,0.496,0.513,0.529,0.546,0.563,0.58,0.597,0.613,0.63,0.647,0.664,0.681,0.697,0.714,0.731,0.748,0.765,0.782,0.798,0.815,0.832,0.849,0.866,0.882,0.899,0.916,0.933,0.95,0.966,0.983,1],\"y\":[0.995,1.052,0.907,0.906,0.915,0.834,0.756,0.846,0.841,0.67,0.665,0.725,0.662,0.61,0.523,0.578,0.504,0.51,0.486,0.489,0.468,0.367,0.419,0.342,0.392,0.404,0.311,0.28,0.308,0.285,0.262,0.226,0.196,0.27,0.104,0.164,0.12,0.078,0.044,0.187,0.147,0.087,0.087,0.094,-0.101,0.118,0.121,0.048,0.022,0.015,-0.087,-0.026,0.042,0.03,0.032,-0.002,0.058,-0.102,0.023,-0.019,-0.097,-0.013,-0.026,-0.007,0.018,0.008,-0.01,0.056,0.076,0.072,0.054,0.118,0.031,0.045,0.003,0.077,0.127,0.141,0.051,0.174,0.119,0.218,0.158,0.112,0.142,0.141,0.167,0.21,0.286,0.289,0.368,0.329,0.253,0.257,0.344,0.314,0.399,0.399,0.474,0.484,0.459,0.491,0.508,0.436,0.64,0.622,0.632,0.652,0.566,0.666,0.702,0.718,0.715,0.75,0.853,0.882,0.91,0.986,1.016,0.993],\"xlab\":\"x\",\"ylab\":\"y\"}};</script>\n\n\n\n::: {.corr-widget}\n<div class=\"cw-shell\">\n<div class=\"cw-picker\" id=\"cw-picker\"></div>\n<div class=\"cw-main\">\n<div class=\"cw-canvas-wrap\">\n<canvas id=\"cw-canvas\" width=\"560\" height=\"420\" aria-label=\"Interactive scatter plot\"></canvas>\n<p class=\"cw-hint\">Click the plot to add an outlier · <button id=\"cw-reset\" type=\"button\">Reset</button></p>\n</div>\n<div class=\"cw-readout\" id=\"cw-readout\"></div>\n</div>\n</div>\n\n<style>\n.corr-widget {\n  --cw-bg: #ffffff; --cw-fg: #123b5d; --cw-muted: #6b7c8c;\n  --cw-line: #d9e2e8; --cw-accent: #167d78; --cw-warn: #b8634f;\n  --cw-chip: #eef4f5;\n  margin: 2rem 0 2.5rem; padding: 1.25rem; border: 1px solid var(--cw-line);\n  border-radius: .9rem; background: var(--cw-bg); color: var(--cw-fg);\n}\nbody.quarto-dark .corr-widget {\n  --cw-bg: #1f2933; --cw-fg: #e6edf3; --cw-muted: #9fb0bd;\n  --cw-line: #37444f; --cw-accent: #4fd1c5; --cw-warn: #f0876a;\n  --cw-chip: #2b3742;\n}\n.cw-picker { display: flex; flex-wrap: wrap; gap: .4rem; margin-bottom: 1rem; }\n.cw-picker button {\n  font: inherit; font-size: .85rem; padding: .35rem .8rem; cursor: pointer;\n  border: 1px solid var(--cw-line); background: var(--cw-chip);\n  color: var(--cw-fg); border-radius: 2rem; transition: all .15s;\n}\n.cw-picker button:hover { border-color: var(--cw-accent); }\n.cw-picker button[aria-pressed=\"true\"] {\n  background: var(--cw-accent); border-color: var(--cw-accent); color: #fff; font-weight: 600;\n}\n.cw-main { display: grid; grid-template-columns: minmax(0,1.4fr) minmax(0,1fr); gap: 1.5rem; align-items: start; }\n.cw-canvas-wrap canvas {\n  width: 100%; height: auto; display: block; cursor: crosshair;\n  border: 1px solid var(--cw-line); border-radius: .5rem; background: var(--cw-bg);\n}\n.cw-hint { font-size: .8rem; color: var(--cw-muted); margin: .5rem 0 0; }\n.cw-hint button {\n  font: inherit; font-size: .8rem; padding: .15rem .6rem; cursor: pointer;\n  border: 1px solid var(--cw-line); background: var(--cw-chip);\n  color: var(--cw-fg); border-radius: .3rem;\n}\n.cw-metric { margin-bottom: .9rem; }\n.cw-metric-top { display: flex; justify-content: space-between; align-items: baseline; font-size: .85rem; }\n.cw-metric-name { color: var(--cw-muted); }\n.cw-metric-val { font-variant-numeric: tabular-nums; font-weight: 700; font-size: 1.15rem; }\n.cw-bar { position: relative; height: 7px; background: var(--cw-chip); border-radius: 4px; margin-top: .3rem; overflow: hidden; }\n.cw-bar-mid { position: absolute; left: 50%; top: 0; bottom: 0; width: 1px; background: var(--cw-line); }\n.cw-bar-fill { position: absolute; top: 0; bottom: 0; border-radius: 4px; transition: all .18s ease; }\n.cw-pairs { border-top: 1px solid var(--cw-line); margin-top: 1rem; padding-top: .8rem; font-size: .85rem; }\n.cw-pairs div { display: flex; justify-content: space-between; padding: .15rem 0; }\n.cw-pairs .cw-pv { font-variant-numeric: tabular-nums; font-weight: 600; }\n.cw-note { font-size: .78rem; color: var(--cw-muted); margin-top: .8rem; line-height: 1.5; }\n@media (max-width: 760px) { .cw-main { grid-template-columns: 1fr; } }\n</style>\n\n<script>\n(function () {\n  var DATA = window.CORR_DATA;\n  if (!DATA) return;\n\n  var order = [\"dino\", \"circle\", \"star\", \"x_shape\", \"slant_up\", \"penguins\", \"linear\", \"parabola\"];\n  var keys  = order.filter(function (k) { return DATA[k]; });\n  var current = keys[0];\n  var extra = [];   // user-added outliers, cleared on dataset change / reset\n\n  // ---- statistics, all computed client-side ----------------------------\n  function pearson(x, y) {\n    var n = x.length, mx = 0, my = 0, i;\n    for (i = 0; i < n; i++) { mx += x[i]; my += y[i]; }\n    mx /= n; my /= n;\n    var sxy = 0, sxx = 0, syy = 0, dx, dy;\n    for (i = 0; i < n; i++) {\n      dx = x[i] - mx; dy = y[i] - my;\n      sxy += dx * dy; sxx += dx * dx; syy += dy * dy;\n    }\n    return (sxx === 0 || syy === 0) ? NaN : sxy / Math.sqrt(sxx * syy);\n  }\n\n  // Average ranks, so ties are handled the way R's rank() handles them.\n  function ranks(v) {\n    var idx = v.map(function (val, i) { return [val, i]; });\n    idx.sort(function (a, b) { return a[0] - b[0]; });\n    var r = new Array(v.length), i = 0;\n    while (i < idx.length) {\n      var j = i;\n      while (j + 1 < idx.length && idx[j + 1][0] === idx[i][0]) j++;\n      var avg = (i + j) / 2 + 1;\n      for (var k = i; k <= j; k++) r[idx[k][1]] = avg;\n      i = j + 1;\n    }\n    return r;\n  }\n\n  function spearman(x, y) { return pearson(ranks(x), ranks(y)); }\n\n  // Explicit O(n^2) pair classification - the same algorithm as the R version.\n  function pairCounts(x, y) {\n    var n = x.length, C = 0, D = 0, Tx = 0, Ty = 0;\n    for (var i = 0; i < n - 1; i++) {\n      for (var j = i + 1; j < n; j++) {\n        var dx = x[i] - x[j], dy = y[i] - y[j], s = Math.sign(dx) * Math.sign(dy);\n        if (s > 0) C++;\n        else if (s < 0) D++;\n        else if (dx === 0 && dy === 0) { /* tied on both */ }\n        else if (dx === 0) Tx++;\n        else Ty++;\n      }\n    }\n    return { C: C, D: D, Tx: Tx, Ty: Ty };\n  }\n\n  function tauB(p) {\n    var d = Math.sqrt((p.C + p.D + p.Tx) * (p.C + p.D + p.Ty));\n    return d === 0 ? NaN : (p.C - p.D) / d;\n  }\n\n  // ---- rendering --------------------------------------------------------\n  var canvas = document.getElementById(\"cw-canvas\");\n  var ctx = canvas.getContext(\"2d\");\n  var PAD = 46;\n\n  function css(name) {\n    return getComputedStyle(document.querySelector(\".corr-widget\")).getPropertyValue(name).trim();\n  }\n\n  function series() {\n    var d = DATA[current];\n    var x = d.x.slice(), y = d.y.slice();\n    for (var i = 0; i < extra.length; i++) { x.push(extra[i][0]); y.push(extra[i][1]); }\n    return { x: x, y: y, n0: d.x.length, meta: d };\n  }\n\n  function scales(s) {\n    var xs = s.x, ys = s.y;\n    var x0 = Math.min.apply(null, xs), x1 = Math.max.apply(null, xs);\n    var y0 = Math.min.apply(null, ys), y1 = Math.max.apply(null, ys);\n    var px = (x1 - x0) * 0.08 || 1, py = (y1 - y0) * 0.08 || 1;\n    x0 -= px; x1 += px; y0 -= py; y1 += py;\n    var W = canvas.width, H = canvas.height;\n    return {\n      sx: function (v) { return PAD + (v - x0) / (x1 - x0) * (W - PAD * 1.4); },\n      sy: function (v) { return H - PAD - (v - y0) / (y1 - y0) * (H - PAD * 1.5); },\n      ix: function (p) { return x0 + (p - PAD) / (W - PAD * 1.4) * (x1 - x0); },\n      iy: function (p) { return y0 + (H - PAD - p) / (H - PAD * 1.5) * (y1 - y0); }\n    };\n  }\n\n  function draw() {\n    var s = series(), sc = scales(s);\n    var fg = css(\"--cw-fg\"), line = css(\"--cw-line\"),\n        accent = css(\"--cw-accent\"), warn = css(\"--cw-warn\"), muted = css(\"--cw-muted\");\n\n    ctx.clearRect(0, 0, canvas.width, canvas.height);\n\n    // axes\n    ctx.strokeStyle = line; ctx.lineWidth = 1;\n    ctx.beginPath();\n    ctx.moveTo(PAD, PAD * 0.5); ctx.lineTo(PAD, canvas.height - PAD);\n    ctx.lineTo(canvas.width - PAD * 0.4, canvas.height - PAD);\n    ctx.stroke();\n\n    // axis labels\n    ctx.fillStyle = muted; ctx.font = \"12px system-ui, sans-serif\";\n    ctx.textAlign = \"center\";\n    ctx.fillText(s.meta.xlab, (canvas.width + PAD) / 2, canvas.height - 12);\n    ctx.save();\n    ctx.translate(14, (canvas.height - PAD) / 2);\n    ctx.rotate(-Math.PI / 2);\n    ctx.fillText(s.meta.ylab, 0, 0);\n    ctx.restore();\n\n    // original points\n    ctx.fillStyle = accent;\n    for (var i = 0; i < s.n0; i++) {\n      ctx.beginPath();\n      ctx.arc(sc.sx(s.x[i]), sc.sy(s.y[i]), 3.1, 0, Math.PI * 2);\n      ctx.fill();\n    }\n    // user-added outliers, visually distinct\n    ctx.fillStyle = warn;\n    for (var j = s.n0; j < s.x.length; j++) {\n      ctx.beginPath();\n      ctx.arc(sc.sx(s.x[j]), sc.sy(s.y[j]), 5.4, 0, Math.PI * 2);\n      ctx.fill();\n      ctx.strokeStyle = css(\"--cw-bg\"); ctx.lineWidth = 1.6; ctx.stroke();\n    }\n    return s;\n  }\n\n  function bar(v) {\n    // Map a coefficient in [-1,1] onto a centre-anchored bar.\n    var pct = Math.min(Math.abs(v), 1) * 50;\n    var left = v >= 0 ? 50 : 50 - pct;\n    var col = Math.abs(v) < 0.15 ? \"var(--cw-muted)\" : \"var(--cw-accent)\";\n    return '<div class=\"cw-bar\"><div class=\"cw-bar-mid\"></div>' +\n           '<div class=\"cw-bar-fill\" style=\"left:' + left + '%;width:' + pct +\n           '%;background:' + col + '\"></div></div>';\n  }\n\n  function metric(name, v) {\n    return '<div class=\"cw-metric\"><div class=\"cw-metric-top\">' +\n           '<span class=\"cw-metric-name\">' + name + '</span>' +\n           '<span class=\"cw-metric-val\">' + (isNaN(v) ? \"--\" : v.toFixed(3)) + '</span>' +\n           '</div>' + bar(v) + '</div>';\n  }\n\n  function update() {\n    var s = draw();\n    var r = pearson(s.x, s.y), rho = spearman(s.x, s.y);\n    var p = pairCounts(s.x, s.y), t = tauB(p);\n\n    var html =\n      metric(\"Pearson r\", r) +\n      metric(\"Spearman rho\", rho) +\n      metric(\"Kendall tau-b\", t) +\n      '<div class=\"cw-pairs\">' +\n        '<div><span>n</span><span class=\"cw-pv\">' + s.x.length +\n          (extra.length ? \" (+\" + extra.length + \" added)\" : \"\") + '</span></div>' +\n        '<div><span>Concordant C</span><span class=\"cw-pv\">' + p.C.toLocaleString() + '</span></div>' +\n        '<div><span>Discordant D</span><span class=\"cw-pv\">' + p.D.toLocaleString() + '</span></div>' +\n        '<div><span>C - D</span><span class=\"cw-pv\">' + (p.C - p.D).toLocaleString() + '</span></div>' +\n      '</div>' +\n      '<p class=\"cw-note\">All three coefficients are computed in your browser from the ' +\n      'same definitions given above, including average ranks for ties and the ' +\n      'tie-corrected tau-b denominator.</p>';\n\n    document.getElementById(\"cw-readout\").innerHTML = html;\n  }\n\n  // ---- controls ---------------------------------------------------------\n  var picker = document.getElementById(\"cw-picker\");\n  keys.forEach(function (k) {\n    var b = document.createElement(\"button\");\n    b.type = \"button\";\n    b.textContent = DATA[k].label;\n    b.setAttribute(\"aria-pressed\", k === current ? \"true\" : \"false\");\n    b.addEventListener(\"click\", function () {\n      current = k; extra = [];\n      Array.prototype.forEach.call(picker.children, function (c) {\n        c.setAttribute(\"aria-pressed\", c === b ? \"true\" : \"false\");\n      });\n      update();\n    });\n    picker.appendChild(b);\n  });\n\n  canvas.addEventListener(\"click\", function (ev) {\n    var rect = canvas.getBoundingClientRect();\n    // The canvas is CSS-scaled, so map client pixels back to canvas pixels.\n    var px = (ev.clientX - rect.left) * (canvas.width / rect.width);\n    var py = (ev.clientY - rect.top) * (canvas.height / rect.height);\n    var sc = scales(series());\n    extra.push([sc.ix(px), sc.iy(py)]);\n    update();\n  });\n\n  document.getElementById(\"cw-reset\").addEventListener(\"click\", function () {\n    extra = []; update();\n  });\n\n  update();\n  // Redraw on theme toggle so canvas colours track the active Quarto theme.\n  new MutationObserver(update).observe(document.body, {\n    attributes: true, attributeFilter: [\"class\"]\n  });\n})();\n</script>\n:::\n\nThree things are worth trying deliberately:\n\n1. **Select `parabola`.** All three coefficients sit near zero ($r = -0.002$,\n   $\\rho = 0.004$, $\\tau_b = 0.014$) while the relationship is deterministic. The pair\n   counts show the mechanism directly: $C = 3{,}618$ against $D = 3{,}517$.\n2. **Select `linear + noise`, then add one point in a far corner.** Pearson drops from\n   $0.959$ to roughly $0.73$; $\\tau_b$ moves from $0.826$ to about $0.80$. One point\n   costs Pearson around a quarter of its estimate and Kendall a few percent.\n3. **Select `dino` and watch $C - D$.** A single added point shifts it by only one or two\n   hundred out of 10,011 pairs, because that point participates in just $n - 1$ of them.\n   Keep clicking in the same corner, though, and $\\tau_b$ does eventually climb — bounded\n   influence per observation is not immunity to systematic contamination.\n\n## Q: Which metric should I use for my AI/ML research?\n\n\n\n```{mermaid}\nflowchart TD\n  A[Two continuous variables] --> B{Is the relationship<br/>plausibly monotone?}\n  B -->|No / unknown| C[Use dCor or MI<br/>with a permutation null]\n  B -->|Yes| D{Outliers, heavy tails,<br/>or ordinal data?}\n  D -->|Yes| E[Kendall's tau<br/>or Somers' d]\n  D -->|No| F{Is linearity itself<br/>the claim?}\n  F -->|Yes| G[Pearson's r]\n  F -->|No| H[Spearman's rho]\n  C --> I{Is n large enough<br/>for adequate power?}\n  I -->|No| J[Report the null<br/>calibration honestly]\n  I -->|Yes| K[Report effect + p-value]\n\n  classDef robust fill:#dcefee,stroke:#167d78,color:#123b5d\n  classDef fragile fill:#f7efe4,stroke:#b8634f,color:#49352e\n  class C,E,H,J,K robust\n  class G fragile\n```\n\n\n\n| Metric | Assumes | Detects | Outlier-robust | Cost | Use when |\n|---|---|---|---|---|---|\n| **Pearson's $r$** | Linearity; finite variance | Linear association only | **No** | $O(n)$ | Linearity is the actual scientific claim, and the data supports it |\n| **Spearman's $\\rho$** | Monotonicity | Monotone association | Yes | $O(n \\log n)$ | Monotone but non-linear relationships; a robust default |\n| **Kendall's $\\tau$** | Monotonicity | Concordance directly | **Most** | $O(n^2)$ naive | Small $n$, many ties, ordinal data, heavy contamination |\n| **Somers' $d$** | Monotonicity | Directional concordance | Most | $O(n^2)$ | An asymmetric predictor→outcome relationship; equals the rank-based reading of a binary AUC |\n| **Distance correlation** | None beyond finite moments | Any dependence | No | $O(n^2)$ | Non-monotone structure is plausible **and** $n$ is comfortably large |\n| **Mutual information** | None (needs discretisation) | Any dependence | Depends on binning | $O(n^2)$ | Arbitrary dependence; always with a bin sweep and a permutation null |\n\nFour rules follow from the results above.\n\n**1. Never report a general-association measure without its null.** dCor and MI have\npositive bias floors. \"dCor $= 0.16$\" is not evidence of anything; \"dCor $= 0.16$,\npermutation $p = 0.17$, $B = 999$\" is an interpretable — and in that case negative —\nresult.\n\n**2. Prefer $\\tau$ over $r$ whenever magnitudes are not trustworthy.** One bad record in\n343 cost Pearson 96% of its estimate and Kendall 1.6%. In high-throughput assays where\nmanual inspection of every point is impossible, bounded influence is worth more than\nstatistical efficiency.\n\n**3. Stratify before you correlate.** The penguin data produced both an inflated pooled\ncorrelation and a full sign reversal. Neither is a coefficient-selection problem. For\nthis study, clinical group and tissue type are the stratifying variables that must be\nhandled in the model rather than averaged over.\n\n**4. Zero has a specific meaning, and it is narrow.** $\\tau = 0$ means $C = D$. It does\nnot mean independence. The dinosaur has $\\tau = -0.048$ and a completely determined\nshape.\n\nFor the methylation–sIgA work specifically, tissue–plasma agreement is a **concordance**\nquestion — does a participant ranked high on a tissue marker also rank high in plasma? —\nand $\\tau$ or Somers' $d$ answers it directly, without assuming the paired measurements\nare linearly related or comparably scaled. See\n[limma versus DSS](../limma-versus-dss-for-methylation.qmd) for how the same\ndistribution-shape concerns drive the choice of differential-methylation engine.\n\n::: {.callout-tip title=\"Reproducibility notes\"}\nEvery coefficient in this post is computed twice: once from a hand-written\nimplementation and once from base R, with `stopifnot(all.equal(...))` asserting they\nagree. A mismatch aborts the render, so a published page is evidence the implementations\nare correct.\n\n**Deviations from a conventional setup**, for anyone rerunning this:\n\n- `dplyr` + `ggplot2` are loaded individually rather than via `tidyverse`; this site\n  builds on R 4.0.5, where the meta-package is not installed.\n- Tables use `knitr::kable()` rather than `gt` or `kableExtra`.\n- Distance correlation and mutual information are written from scratch rather than taken\n  from `energy` and `infotheo`, which both need compilation. The hand-written versions\n  are validated against known cases in the table above.\n- Permutation tests use $B = 999$ and a fixed seed (`set.seed(2026)`), so the\n  $p$-values are reproducible but carry Monte Carlo error of roughly $\\pm 0.01$.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Session information\"}\nkable(\n  data.frame(\n    Component = c(\"R\", \"ggplot2\", \"dplyr\", \"datasauRus\", \"palmerpenguins\"),\n    Version = c(\n      paste(R.version$major, R.version$minor, sep = \".\"),\n      as.character(packageVersion(\"ggplot2\")),\n      as.character(packageVersion(\"dplyr\")),\n      as.character(packageVersion(\"datasauRus\")),\n      as.character(packageVersion(\"palmerpenguins\"))\n    )\n  ),\n  caption = \"Environment used to render this post.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Environment used to render this post.\n\n|Component      |Version |\n|:--------------|:-------|\n|R              |4.0.5   |\n|ggplot2        |3.3.5   |\n|dplyr          |1.0.8   |\n|datasauRus     |0.1.9   |\n|palmerpenguins |0.1.1   |\n\n\n:::\n:::\n\n\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}